/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.apirestassured.api.teste;

import com.apirestassured.api.dominio.Usuario;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class UsuarioTest extends BaseTest{
    private static final String LISTA_USUARIO_ENDPOINT = "/users";
    private static final String CRIAR_USUARIO_ENDPOINT = "/users";
    @Test
    public void deveTestarListaDeTodosUsuarios() {
        given().params("page", "2")
                .when()
                .get(LISTA_USUARIO_ENDPOINT)
                .then()
                .statusCode(HttpStatus.SC_OK)
                .body("page", is(2))
                .body("data", is(notNullValue()));
    }

    @Test
    public void deveCriarUmUsuario() {
        Usuario usuario = new Usuario("carolina", "analista de teste", "teste@teste.com", "123456c");
        given()

                .body(usuario)
                .when()
                .post(CRIAR_USUARIO_ENDPOINT)
                .then()
                .statusCode(HttpStatus.SC_CREATED)
                .body("name", is("carolina"));
    }
}
